#pragma once

#include <iostream>

#define TRANSFORM_PACKET 0
#define ANIMATION_PACKET 1
#define AI_STATE_PACKET 2
#define SPELL_PACKET 3
#define AI_TRANSFORM_PACKET 4
#define CHARGING_PACKET 5
#define QUICKBLEND_PACKET 6
#define DAMAGE_PACKET 7
#define CHANGESPELLS_PACKET 8